# Creates a kind cluster with a registry.
# Examples: https://github.com/tilt-dev/ctlptl/tree/main/examples

apiVersion: ctlptl.dev/v1alpha1
kind: Registry
port: 5002
listenAddress: 127.0.0.1
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry