apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile
  labels:
    app: mobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
        - name: mobile
          image: mobile
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mobile
spec:
  selector:
    app: mobile
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mobile-cert
spec:
  secretName: mobile-tls
  duration: 2160h
  renewBefore: 360h
  commonName: mobile.local
  dnsNames:
  - mobile.local
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mobile.local
    secretName: mobile-tls
  rules:
  - host: mobile.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mobile
            port:
              number: 8081